version: '2'
services:
    mongodb:
        image: "mongo"
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017
    elasticsearch:
        image: "elasticsearch:7.0.0"
        container_name: "elasticsearch"
        volumes:
          - ./data/elasticsearcn:/data/elasticsearch
        ports:
            - 9200:9200
            - 9300:9300
        environment:
            - "discovery.type=single-node"
